wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714433483.70219
    t:
      1:
      - 55
      - 105
      3:
      - 14
      - 23
      4: 3.11.4
      5: 0.15.10
      8:
      - 5
